use scc::HashMap;

include!(concat!(env!("OUT_DIR"), "/atom.rs"));

#[derive(Debug, PartialEq, Eq, Hash)]
pub enum AtomKind {
    String,
    Global,
    Symbol,
    Private,
}

#[derive(Debug, PartialEq, Eq, Hash)]
pub struct AtomIndex {
    pub hash: u32,
    pub kind: AtomKind,
}

impl AtomIndex {
    pub fn new(hash: u32, kind: AtomKind) -> Self {
        Self { hash, kind }
    }
}

pub fn init() -> HashMap<AtomIndex, Atom> {
    let map = HashMap::default();

    macro_rules! atomref {
        ($name:tt, $kind:expr) => {
            Atom::from($name)
        };
        ($kind:expr, $($name:tt) *) => {$(
            let atom = Atom::from($name);
            let index = AtomIndex::new(atom.get_hash(), $kind);
            map.insert(index, atom).unwrap();
        )*};
    }

    atomref!(AtomKind::Private, "<brand>");
    atomref!(AtomKind::String,
        "null"
        "false"
        "true"
        "if"
        "else"
        "return"
        "var"
        "this"
        "delete"
        "void"
        "typeof"
        "new"
        "in"
        "instanceof"
        "do"
        "while"
        "for"
        "break"
        "continue"
        "switch"
        "case"
        "default"
        "throw"
        "try"
        "catch"
        "finally"
        "function"
        "debugger"
        "with"
        "class"
        "const"
        "enum"
        "export"
        "extends"
        "import"
        "super"
        "implements"
        "interface"
        "let"
        "package"
        "private"
        "protected"
        "public"
        "static"
        "yield"
        "await"
        ""
        "length"
        "fileName"
        "lineNumber"
        "message"
        "errors"
        "stack"
        "name"
        "toString"
        "toLocaleString"
        "valueOf"
        "eval"
        "prototype"
        "constructor"
        "configurable"
        "writable"
        "enumerable"
        "value"
        "get"
        "set"
        "of"
        "__proto__"
        "undefined"
        "number"
        "boolean"
        "string"
        "object"
        "symbol"
        "integer"
        "unknown"
        "arguments"
        "callee"
        "caller"
        "<eval>"
        "<ret>"
        "<var>"
        "<arg_var>"
        "<with>"
        "lastIndex"
        "target"
        "index"
        "input"
        "defineProperties"
        "apply"
        "join"
        "concat"
        "split"
        "construct"
        "getPrototypeOf"
        "setPrototypeOf"
        "isExtensible"
        "preventExtensions"
        "has"
        "deleteProperty"
        "defineProperty"
        "getOwnPropertyDescriptor"
        "ownKeys"
        "add"
        "done"
        "next"
        "values"
        "source"
        "flags"
        "global"
        "unicode"
        "raw"
        "new.target"
        "this.active_func"
        "<home_object>"
        "<computed_field>"
        "<static_computed_field>"
        "<class_fields_init>"
        "<brand>"
        "#constructor"
        "as"
        "from"
        "meta"
        "*default*"
        "*"
        "Module"
        "then"
        "resolve"
        "reject"
        "promise"
        "proxy"
        "revoke"
        "exec"
        "groups"
        "status"
        "reason"
        "globalThis"
        "bigint"
        "bigfloat"
        "bigdecimal"
        "roundingMode"
        "maximumSignificantDigits"
        "maximumFractionDigits"
        "not-equal"
        "timed-out"
        "ok"
        "toJSON"
        "Object"
        "Array"
        "Error"
        "Number"
        "String"
        "Boolean"
        "Symbol"
        "Arguments"
        "Math"
        "JSON"
        "Date"
        "Function"
        "GeneratorFunction"
        "ForInIterator"
        "RegExp"
        "ArrayBuffer"
        "SharedArrayBuffer"
        "Uint8ClampedArray"
        "Int8Array"
        "Uint8Array"
        "Int16Array"
        "Uint16Array"
        "Int32Array"
        "Uint32Array"
        "BigInt64Array"
        "BigUint64Array"
        "Float32Array"
        "Float64Array"
        "DataView"
        "BigInt"
        "BigFloat"
        "BigFloatEnv"
        "BigDecimal"
        "OperatorSet"
        "Operators"
        "Map"
        "Set"
        "WeakMap"
        "WeakSet"
        "Map Iterator"
        "Set Iterator"
        "Array Iterator"
        "String Iterator"
        "RegExp String Iterator"
        "Generator"
        "Proxy"
        "Promise"
        "PromiseResolveFunction"
        "PromiseRejectFunction"
        "AsyncFunction"
        "AsyncFunctionResolve"
        "AsyncFunctionReject"
        "AsyncGeneratorFunction"
        "AsyncGenerator"
        "EvalError"
        "RangeError"
        "ReferenceError"
        "SyntaxError"
        "TypeError"
        "URIError"
        "InternalError"
    );
    atomref!(AtomKind::Symbol,
        "Symbol.toPrimitive"
        "Symbol.iterator"
        "Symbol.match"
        "Symbol.matchAll"
        "Symbol.replace"
        "Symbol.search"
        "Symbol.split"
        "Symbol.toStringTag"
        "Symbol.isConcatSpreadable"
        "Symbol.hasInstance"
        "Symbol.species"
        "Symbol.unscopables"
        "Symbol.asyncIterator"
        "Symbol.operatorSet"
    );

    map
}
